#person:
#  lastName: zhangsan
#  age: 12
#  boos: false
#  brith: 2018-10-9
#  list1: [1,2,3,4]
#  list2:
#    - AA
#    - BB
#  maps1: {m1: v1,m2: v2}
#  maps2:
#    m3: v3
#    m4: v4
#  dog:
#    age: 2
#    name: 花花

